-- 增量列（由 alter.all.v1.0.csv 生成，H2 方言）
ALTER TABLE CLOUD_ACCOUNT ADD IF NOT EXISTS `extraKey` CLOB comment '额外凭证(加密)';
ALTER TABLE CLOUD_INSTANCE ADD IF NOT EXISTS `regionId` VARCHAR(50) comment '区域';
ALTER TABLE CLOUD_INSTANCE ADD IF NOT EXISTS `zoneId` VARCHAR(50) comment '可用区';
ALTER TABLE CLOUD_INSTANCE ADD IF NOT EXISTS `instanceType` VARCHAR(50) comment '实例规格';
ALTER TABLE CLOUD_INSTANCE ADD IF NOT EXISTS `cpu` INTEGER comment 'CPU核数';
ALTER TABLE CLOUD_INSTANCE ADD IF NOT EXISTS `memory` INTEGER comment '内存(MB)';
ALTER TABLE CLOUD_INSTANCE ADD IF NOT EXISTS `osName` VARCHAR(200) comment '操作系统';
ALTER TABLE CLOUD_INSTANCE ADD IF NOT EXISTS `expireTime` VARCHAR(50) comment '到期时间';
ALTER TABLE CLOUD_INSTANCE ADD IF NOT EXISTS `chargeType` VARCHAR(30) comment '计费类型';
ALTER TABLE CLOUD_INSTANCE ADD IF NOT EXISTS `tags` CLOB comment '标签(JSON)';
