-- 索引（由 index.all.v1.0.csv 生成，H2 方言）
CREATE UNIQUE INDEX IF NOT EXISTS SYS_USER_SALT_IDX ON PUBLIC.SYS_USER (salt);
CREATE INDEX IF NOT EXISTS DIR_TASK_ID ON PUBLIC.STORAGE_STATIC_FILE (staticDir,scanTaskId);
CREATE INDEX IF NOT EXISTS DIR_ABS_PATH ON PUBLIC.STORAGE_STATIC_FILE (staticDir,absolutePath);
CREATE INDEX IF NOT EXISTS DIR_PARENT_PATH ON PUBLIC.STORAGE_STATIC_FILE (staticDir,parentAbsolutePath);
CREATE INDEX IF NOT EXISTS TRIGGER_TOKEN_TYPE ON PUBLIC.TRIGGER_TOKEN_LOG (type);
CREATE INDEX IF NOT EXISTS TRIGGER_TOKEN_USER_ID ON PUBLIC.TRIGGER_TOKEN_LOG (userId);
